# Generated by Django 5.2.7 on 2025-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_billinghistory_status_remove_order_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='status',
            field=models.CharField(default='Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
