# Generated by Django 5.2.7 on 2025-11-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_billinghistory_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinghistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
