# Generated by Django 5.2.10 on 2026-02-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, default='My Restaurant', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=20)),
                ('avatar_initials', models.CharField(blank=True, max_length=2)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('ai_model', models.CharField(default='gemini-2.0-flash', max_length=50)),
                ('gemini_api_key', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_address', models.TextField(blank=True)),
                ('restaurant_phone', models.CharField(blank=True, max_length=20)),
                ('restaurant_email', models.EmailField(blank=True, max_length=254)),
                ('business_hours', models.TextField(blank=True)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('default_tip_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your business!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
